# 판다스(pandas) 심화 

In [5]:
import numpy as np
import pandas as pd

print("DataFrame: ")

data = {'col1':[2, 1, 9, 8, 7, 4], 
        'col2':['A', 'A', 'B', np.nan, 'D', 'C'], 
        'col3':[0, 1, 9, 4, 2, 3]
       }

index = [1, 3, 2, 5, 0, 4]
df = pd.DataFrame(data, index=index)

df

DataFrame: 


col1 col2  col3
1     2    A     0
3     1    A     1
2     9    B     9
5     8  NaN     4
0     7    D     2
4     4    C     3

## 데이터프레임 정렬

In [9]:
# index axis=0(행) 을 축으로 정렬

df = df.sort_index(axis=0)
df

col3 col2  col1
0     2    D     7
1     0    A     2
2     9    B     9
3     1    A     1
4     3    C     4
5     4  NaN     8

- ascending -> 오름차순
- descending -> 내림차순

In [12]:
# index axis=1(열) 을 축으로 정렬, 내림차순

df = df.sort_index(axis=1, ascending=False)
df

col3 col2  col1
0     2    D     7
1     0    A     2
2     9    B     9
3     1    A     1
4     3    C     4
5     4  NaN     8

In [14]:
# sort_values 1  

sorted_df1 = df.sort_values('col1', ascending=True)
sorted_df1

col3 col2  col1
3     1    A     1
1     0    A     2
4     3    C     4
0     2    D     7
5     4  NaN     8
2     9    B     9

In [15]:
# sort_values 2

sorted_df2 = df.sort_values(['col2', 'col1'], ascending=[True, False])
sorted_df2

col3 col2  col1
1     0    A     2
3     1    A     1
2     9    B     9
4     3    C     4
0     2    D     7
5     4  NaN     8

In [16]:
x = np.random.randint(1, 5, size=(10,5))
x

array([[2, 2, 4, 2, 2],
       [1, 4, 1, 2, 2],
       [3, 2, 3, 3, 4],
       [4, 1, 2, 4, 4],
       [4, 3, 1, 2, 1],
       [3, 1, 4, 1, 3],
       [1, 1, 2, 3, 1],
       [3, 4, 4, 2, 2],
       [4, 4, 3, 2, 4],
       [4, 2, 1, 4, 4]], dtype=int32)

In [17]:
x = np.random.rand(10,5)
x

array([[0.85143521, 0.30870959, 0.61574411, 0.48780667, 0.36159109],
       [0.54196383, 0.11428925, 0.77028875, 0.84593967, 0.28084392],
       [0.75788963, 0.99544142, 0.26080746, 0.31396365, 0.23038386],
       [0.86104086, 0.32190793, 0.74585508, 0.25436837, 0.07500873],
       [0.16221884, 0.12157487, 0.37616098, 0.4039399 , 0.87566115],
       [0.54150293, 0.7726981 , 0.7680858 , 0.82827109, 0.51767938],
       [0.81707335, 0.09880616, 0.15429896, 0.70150677, 0.60674732],
       [0.24183339, 0.57486349, 0.86317709, 0.33257915, 0.14614609],
       [0.6648091 , 0.61952466, 0.93963578, 0.40188695, 0.50136877],
       [0.08923741, 0.56755512, 0.7099483 , 0.2490686 , 0.18193077]])

In [34]:
x = np.random.normal(5, 3, (10,5)) # 평균이 5, 표준편차 3

print(x)
print(np.mean(x), np.std(x), x.min(), x.max())


[[ 4.81376668 10.93800305  4.954553    5.81813283  5.36736114]
 [ 2.04805821  7.10975862  8.08482307  6.37260823  3.13250181]
 [ 6.17262963  7.58557573  6.43413387  3.49931644  7.24143857]
 [ 6.60913439  4.54980959  4.8883499   6.4281464   8.1928449 ]
 [ 2.29332362  2.49294826  5.45333023  3.27109196  1.37843823]
 [ 4.17589772  5.97515395  6.37913404  8.16039217  9.43515344]
 [ 0.31388552  1.28885721 -2.93422854  5.88272236  4.91890857]
 [ 9.01700636  5.22530432  1.58128795  2.35930016  6.026186  ]
 [-0.30735997  2.53656618  2.47623462  3.92666796  3.3047959 ]
 [ 5.17749928  9.01329096  4.78054661  5.4664379   7.39131681]]
4.93402071699139 2.689255856331936 -2.934228543754955 10.9380030493287


In [36]:
x = np.array([1,23,3,45,56,456,0,7,56,8,76,4,5678,0,0,0])

print('x의 개수', len(x))
print('x의 개수', np.count_nonzero(x))
print('0의 개수', len(x) - np.count_nonzero(x))

x의 개수 16
x의 개수 12
0의 개수 4


In [41]:
print(np.mean(x))
print(x.mean())

print(np.var(x))
print(x.var())

print(np.std(x))
print(x.std())

print(x.min())
print(x.max())
print(np.median(x)) # 중앙값

400.8125
400.8125
1868246.90234375
1868246.90234375
1366.8382868297733
1366.8382868297733
0
5678
7.5


In [42]:
print(np.percentile(x,0))  # 최소값
print(np.percentile(x,25)) # 제1사분위수
print(np.percentile(x,50)) # 중앙값, 제2사분위수
print(np.percentile(x,75)) # 제3사분위수
print(np.percentile(x,100)) # 최대값

0.0
0.75
7.5
56.0
5678.0


## 데이터 분석용 함수

In [58]:
# 데이터프레임의 index와 columns

import numpy as np
import pandas as pd

data = {
    'korean':[50,60,70,30],
    'math':[30,np.nan,40,20],
}

index = ['a','b','c','d']

df = pd.DataFrame(data, index=index)

print(df.index)
print(df.columns)
df

Index(['a', 'b', 'c', 'd'], dtype='object')
Index(['korean', 'math'], dtype='object')


korean  math
a      50  30.0
b      60   NaN
c      70  40.0
d      30  20.0

In [59]:
# count() 함수

print(df.count(axis=0)) # axis = 0 기본값(생략가능)
print(df.count(axis=1))


korean    4
math      3
dtype: int64
a    2
b    1
c    2
d    2
dtype: int64


In [60]:
# max(), min(), sum(), mean()

print(df.max())
print(df.min())
print(df.sum())
print(df.mean())

print('\n')

print(df.max(axis=1))
print(df.min(axis=1))
print(df.sum(axis=1))
print(df.mean(axis=1))

print('\n')


print(df.mean(axis=1, skipna=False)) # NaN 무시 x

korean    70.0
math      40.0
dtype: float64
korean    30.0
math      20.0
dtype: float64
korean    210.0
math       90.0
dtype: float64
korean    52.5
math      30.0
dtype: float64


a    50.0
b    60.0
c    70.0
d    30.0
dtype: float64
a    30.0
b    60.0
c    40.0
d    20.0
dtype: float64
a     80.0
b     60.0
c    110.0
d     50.0
dtype: float64
a    40.0
b    60.0
c    55.0
d    25.0
dtype: float64


a    40.0
b     NaN
c    55.0
d    25.0
dtype: float64


In [61]:
# 결측값 대체 fillna
avg = df['math'].mean()
df['math'] = df['math'].fillna(avg)
df

korean  math
a      50  30.0
b      60  30.0
c      70  40.0
d      30  20.0

## 그룹으로 묶기 (groupby)

In [84]:
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'key':['A', 'B', 'C', 'A', 'B', 'C'],
    'data1':[1, 2, 3, 1, 2, 3],
    'data2':[4, 4, 6, 0, 6, 1]
    # 'data3':['안녕', 'a', 'b', '하세요', 'pple', '3']
})

print("DataFrame:")
df

DataFrame:


key  data1  data2
0   A      1      4
1   B      2      4
2   C      3      6
3   A      1      0
4   B      2      6
5   C      3      1

In [85]:
df.groupby('key').sum()

data1  data2
key              
A        2      4
B        4     10
C        6      7

In [86]:
df.groupby(['key','data1']).sum()#.reset_index()


data2
key data1       
A   1          4
B   2         10
C   3          7

In [88]:
# df.groupby('key').aggregate([min, np.median, max])

df.groupby('key').aggregate(['min', 'median', 'max'])

data1            data2           
      min median max   min median max
key                                  
A       1    1.0   1     0    2.0   4
B       2    2.0   2     4    5.0   6
C       3    3.0   3     1    3.5   6

In [89]:
df.groupby('key').aggregate({'data1':'min', 'data2':'max'})

data1  data2
key              
A        1      4
B        2      6
C        3      6