In [ ]:
with open('./drive/MyDrive/ReadMe.md', 'w') as f:
    data = f.write('안아줘요')


In [ ]:
!pwd


/content


# NumPy

- ndim: 축의 개수
- shape: 배열의 차원정보
- size: 배열안에있는 원소의 총 개수
- dtype: 배열 원소의 자료형

## 1차원과 속성들

In [ ]:
import numpy as np

narry = np.array(range(5))

print(narry, type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry[3])
print(narry[2:4])

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
3
[2 3]


In [ ]:
narr1 = np.array([1, 2, 3, 4])
narr2 = np.array([1, 2, 'a' ,'b'])
narr3 = np.array([1, 2, 3, 4], dtype='str')

print(narr1, narr1.dtype)
print(narr2, narr2.dtype)
print(narr3, narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [66]:
narr4 = np.zeros(10, dtype='int64')
narr5 = np.full((3, 3), 3)
narr6 = np.ones((2, 2))
narr7 = np.full((3, 3), 'number')
narr8 = np.eye(3)
narr9 = np.linspace(0, 100, 5, endpoint=False, dtype='int64')
narr10 = np.arange(0, 100, 20)


print(narr4, narr4.ndim, narr4.dtype, narr4.shape, narr4.size, type(narr4), '\n')
print(narr5, narr5.ndim, narr5.dtype, narr5.shape, narr5.size, type(narr5), '\n')
print(narr6, narr6.ndim, narr6.dtype, narr6.shape, narr6.size, type(narr6), '\n')
print(narr7, narr7.ndim, narr7.dtype, narr7.shape, narr7.size, type(narr7), '\n')
print(narr8, narr8.ndim, narr8.dtype, narr8.shape, narr8.size, type(narr8), '\n')
print(narr9, narr9.ndim, narr9.dtype, narr9.shape, narr9.size, type(narr9), '\n')
print(narr10, narr10.ndim, narr10.dtype, narr10.shape, narr10.size, type(narr10), '\n')

[0 0 0 0 0 0 0 0 0 0] 1 int64 (10,) 10 <class 'numpy.ndarray'> 

[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'> 

[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'> 

[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'> 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'> 

[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'> 

[ 0 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'> 



## 2차원 배열

In [ ]:
print(list(range(2, 10)))
print(np.arange(2, 10))
range(10)
np.arange(10)


[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.array([[0, 0],[0, 0]])
print(arr1, arr1.dtype, arr1.shape, arr1.size, type(arr1))

[[0 0]
 [0 0]] int64 (2, 2) 4 <class 'numpy.ndarray'>


In [ ]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)
arr3 = np.arange(1, 10).reshape(3, 3)
arr4 = np.arange(1, 11).reshape(2, 5)
arr5 = np.arange(1, 11).reshape(5, 2)
arr6 = np.arange(1, 28).reshape(3, 3, 3)

print('차원', arr2.ndim, '/ 데이터타입', arr2.dtype, '/ 형태', arr2.shape, '/ 크기', arr2.size, type(arr2), '\n', arr2, '\n')
print('차원', arr3.ndim, '/ 데이터타입', arr3.dtype, '/ 형태', arr3.shape, '/ 크기', arr3.size, type(arr3), '\n', arr3, '\n')
print('차원', arr4.ndim, '/ 데이터타입', arr4.dtype, '/ 형태', arr4.shape, '/ 크기', arr4.size, type(arr4), '\n', arr4, '\n')
print('차원', arr5.ndim, '/ 데이터타입', arr5.dtype, '/ 형태', arr5.shape, '/ 크기', arr5.size, type(arr5), '\n', arr5, '\n')
print('차원', arr6.ndim, '/ 데이터타입', arr6.dtype, '/ 형태', arr6.shape, '/ 크기', arr6.size, type(arr6), '\n', arr6, '\n')

차원 2 / 데이터타입 int64 / 형태 (3, 3) / 크기 9 <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

차원 2 / 데이터타입 int64 / 형태 (3, 3) / 크기 9 <class 'numpy.ndarray'> 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 

차원 2 / 데이터타입 int64 / 형태 (2, 5) / 크기 10 <class 'numpy.ndarray'> 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]] 

차원 2 / 데이터타입 int64 / 형태 (5, 2) / 크기 10 <class 'numpy.ndarray'> 
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 

차원 3 / 데이터타입 int64 / 형태 (3, 3, 3) / 크기 27 <class 'numpy.ndarray'> 
 [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]] 



In [78]:
ar1 = np.arange(1, 22).reshape(3, 7)
ar2 = np.arange(1, 8).reshape(7, 1)
ar3 = np.arange(1, 11).reshape(5, 2)
ar4 = np.arange(1, 22).reshape(3, 7)
ar5 = np.arange(1, 13).reshape(4, 3, 1)



print(ar1, '\n==============================')
print(ar2, '\n==============================')
print(ar3, '\n==============================')
print(ar4, '\n==============================')
print(ar5, '\n==============================')


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]] 
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]] 
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]] 


In [68]:
ar1[1][2:5]

array([10, 11, 12])

In [88]:
ar4[0:3, 3:7]

array([[ 4,  5,  6,  7],
       [11, 12, 13, 14],
       [18, 19, 20, 21]])

In [89]:
ar4[1:3, 4:6]

array([[12, 13],
       [19, 20]])

In [92]:
ar4[ar4 > 12]

array([13, 14, 15, 16, 17, 18, 19, 20, 21])

In [94]:
[ar4 > 12]

[array([[False, False, False, False, False, False, False],
        [False, False, False, False, False,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True]])]

In [95]:
ar4[ar4 % 2 == 0 ]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [96]:
ar4 % 2 == 0

array([[False,  True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False,  True],
       [False,  True, False,  True, False,  True, False]])

In [98]:
# np 배열 연산 // shape가 같을 경우 원소별 연산이 가능

np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])

print("덧셈", np1 + np2)
print("뺄셈", np2 - np1)
print("곱셈", np1 * np2)
print("나눗셈", np2 / np1)

덧셈 [ 7  9 11 13 15]
뺄셈 [5 5 5 5 5]
곱셈 [ 6 14 24 36 50]
나눗셈 [6.         3.5        2.66666667 2.25       2.        ]


In [99]:
# 브로드캐스팅

np3 = np1 + 10

print(np3)

[11 12 13 14 15]


In [116]:
br1 = np.arange(1, 10).reshape(3, 3)
br2 = np.array([11,22, 33]) #.reshape(3,1)

# 스칼라와 연산
print(f'{"스칼라와 연산":=^20}\n')
print(br1, '\n')
print(br1+3, '\n')
print(br1+2, '\n')

# 2D와 1D의 연산
print(f'{"2D와 1D의 연산":=^20}\n')
print(br1 + br2, '\n')
print(br1 * br2, '\n')

======스칼라와 연산=======

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

=====2D와 1D의 연산=====

[[12 13 14]
 [26 27 28]
 [40 41 42]] 

[[ 11  22  33]
 [ 88 110 132]
 [231 264 297]] 



In [120]:
ff = np.arange(1, 10).reshape(3, 3)

print(ff, '\n')
print(ff.reshape(9), '\n')
print(ff.flatten(), '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9] 

[1 2 3 4 5 6 7 8 9] 



In [16]:
import datetime as date

tt = str(date.date.today())
tt = tt.replace('-','')
print(tt)

20250225


## Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand(): 0부터 1사이의 균일 분포 난수 생성
- np.random.randn(): 표준 정규 분포 난수 생성
- np.random.normal(): 정규 분포 난수 생성

In [17]:
# randomint

import numpy as np

x = np.random.randint(0, 255, size=(3, 3, 3))
x

array([[[ 55,  65, 203],
        [ 86, 211,  84],
        [ 90, 144,  36]],

       [[227,   9, 191],
        [ 63, 104, 166],
        [ 22, 151,   7]],

       [[107,  86, 165],
        [ 50, 121, 108],
        [  9,  81,  85]]], dtype=int32)

In [18]:
print('평균값: ', np.mean(x), '표준편차: ', np.std(x), '최소값: ', x.min(), '최대값: ', x.max())

평균값:  100.96296296296296 표준편차:  62.315494465502795 최소값:  7 최대값:  227


In [21]:
print(len(x.flatten()))

27


In [24]:
y = np.array([0,13,44,36,48,51,6,87,88,92,10,0,2,12,27])

print(len(y))

print(np.count_nonzero(y))


15
13


# Pandas

- 시리즈(series)
- 데이터프레임(dataframe)

In [2]:
import numpy as np
import pandas as pd

In [10]:
data1 = np.arange(1,11)
print(data1)

data2 = pd.Series(data1)
print(data2, type(data2), data2.values, data2.index)

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 <class 'pandas.core.series.Series'> [ 1  2  3  4  5  6  7  8  9 10] RangeIndex(start=0, stop=10, step=1)


In [15]:
data3 = pd.Series([1,2,3.14,4,5,6,7])#, dtype="float")
print(data3)

0    1.00
1    2.00
2    3.14
3    4.00
4    5.00
5    6.00
6    7.00
dtype: float64


In [17]:
# 판다스 시리즈의 인덱스 설정

data3 = pd.Series([1,2,3,4], index=['a', 'b', 'c', 'd'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [26]:
# 판다스 시리즈 딕셔너리 데이터

population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}

# population_dict.keys()
# population_dict.values()
# population_dict.items()

country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)

# 시리즈 원소에 접근방법
print(country.loc['japan'])
print(country.iloc[1])

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
12622
12622


In [30]:
# 판다스 데이터 프레임

df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], index=['a', 'b', 'c'], columns=['A', 'B', 'C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [1]:
# 테스트

import numpy as np
import pandas as pd


# 두 개의 시리즈 데이터
print("인구수 시리즈 데이터:")

population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}

population = pd.Series(population_dict)
print(population)

print('\n')

print("GDP 시리즈 데이터:")

GDP_dict = {
    'korea':16932000,
    'japan':516700000,
    'china':140925000,
    'usa':2041280000
}

GDP = pd.Series(GDP_dict)

print(GDP)
print('='*25)
print("데이터 프레임 생성:")

country = pd.DataFrame({'population':population, 'gdp':GDP})

country.index.name = "Country" # 인덱스 이름 지정
country.columns.name = "Info" # 컬럼 이름 지정

print(country.index, country.columns)
print(country.values)
print(country.shape, country.size, country.ndim)

country

인구수 시리즈 데이터:
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64


GDP 시리즈 데이터:
korea      16932000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성:
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182   16932000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]]
(4, 2) 8 2


Info     population         gdp
Country                        
korea          5182    16932000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [7]:
# 데이터 프레임의 요소 접근 방법, loc, iloc

country.loc['korea'], country.loc['usa']
country.iloc[2], country.iloc[1]


(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population        12622
 gdp           516700000
 Name: japan, dtype: int64)

In [8]:
country.loc['korea':'japan', :'population']

Info     population
Country            
korea          5182
japan         12622

In [9]:
country.iloc[0:2, :1]

Info     population
Country            
korea          5182
japan         12622

In [10]:
country.iloc[1:4, 1:]

Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000

In [11]:
country.iloc[1:3]

Info     population        gdp
Country                       
japan         12622  516700000
china        141178  140925000

In [4]:
# 컬럼 추가

# country['test']=[11,22,33,44]
# country.drop('test', axis=1) # 컬럼 제거 axis=1

gdpper = country['gdp'] / country['population']
country['gdp_per'] = gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182    16932000   3267.464299
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326
india        142222   150505000   1058.239935
africa       123456     7777777     63.000397

In [2]:
# 행 추가 방법1

country.loc['india'] = [142222, 150505000]
# country.loc['india', 'gdp_per'] = country.loc['india', 'gdp'] / country.loc['india', 'population']
country



Info     population         gdp
Country                        
korea          5182    16932000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000
india        142222   150505000

In [3]:
# 행추가 방법2

africa = pd.Series(data = [123456, 7777777], index=['population', 'gdp'])
country.loc['africa'] = africa

country

Info     population         gdp
Country                        
korea          5182    16932000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000
india        142222   150505000
africa       123456     7777777

In [127]:
country.isnull()

Info     population    gdp  gdp_per
Country                            
korea         False  False    False
japan         False  False    False
china         False  False    False
usa           False  False    False
india         False  False    False
africa        False  False     True

In [5]:
# 열 제거 drop(이름, axis=0)

country = country.drop('africa', axis=0)
country

Info     population         gdp       gdp_per
Country                                      
korea          5182    16932000   3267.464299
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326
india        142222   150505000   1058.239935

In [16]:
# 테스트 1 조건
country[country['population'] > 140000]

Info     population        gdp      gdp_per
Country                                    
china        141178  140925000   998.207936
india        142222  150505000  1058.239935

In [17]:
# 테스트 2 조건, 슬라이싱 (loc, iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:, :'population']

Info     population
Country            
japan         12622
usa           32976

In [62]:
import numpy as np
import pandas as pd

kor_dic = {
    '홍길동':80,
    '박철수':60,
    '김영희':70
}

math_dic = {
    '홍길동':70,
    '박철수':70,
    '김영희':90
}

eng_dic = {
    '홍길동':80,
    '박철수':80,
    '김영희':80
}


kor = pd.Series(kor_dic)
math = pd.Series(math_dic)
eng = pd.Series(eng_dic)


grade = pd.DataFrame({'국어':kor, '수학':math, '영어':eng})

grade



국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [66]:
grade.drop('수학', axis=1).iloc[:1]


국어  영어
홍길동  80  80

In [31]:
grade[grade['수학'] >= 70]

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [33]:
avg = (grade['국어'] + grade['수학'] + grade['영어']) / 3

grade['평균'] = avg

grade

국어  수학  영어         평균
홍길동  80  70  80  76.666667
박철수  60  70  80  70.000000
김영희  70  90  80  80.000000

In [34]:
grade.loc['최자바'] = [55, 95, 70, (55+95+70)/3]

grade

국어    수학    영어         평균
홍길동  80.0  70.0  80.0  76.666667
박철수  60.0  70.0  80.0  70.000000
김영희  70.0  90.0  80.0  80.000000
최자바  55.0  95.0  70.0  73.333333

In [50]:
# 기본적인 방법

data = {
    '이름': ['홍길동', '박철수', '김영희'],
    '국어': [80, 60, 70],
    '수학': [70, 70, 90],
    '영어': [80, 80, 80]
}


grade_1 = pd.DataFrame(data)
grade_1

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [51]:
# 키값쌍으로 리스트에 저장하는 방법

data = [
    {'이름':'홍길동', '국어':80, '수학':70, '영어':80},
    {'이름':'박철수', '국어':60, '수학':70, '영어':80},
    {'이름':'김영희', '국어':70, '수학':90, '영어':80}]

grade_2 = pd.DataFrame(data)
grade_2

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [53]:
# 리스트에 튜풀로 저장하는 방법

data = [
    ('홍길동', 80, 70, 80),
    ('박철수', 60, 70, 80),
    ('김영희', 70, 90, 80)
]

grade_3 = pd.DataFrame(data, columns=['이름', '국어', '수학', '영어'])
grade_3

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [68]:
import numpy as np

data = np.array([['홍길동', 80, 70, 80], ['박철수', 60, 70, 80], ['김영희', 70, 90, 80]])
grade_4 = pd.DataFrame(data, columns=['이름', '국어', '수학', '영어'])
grade_4

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [73]:
grade_4[(grade_4['국어'].astype(int) >= 70)]

이름  국어  수학  영어
0  홍길동  80  70  80
2  김영희  70  90  80